#!/usr/bin/env bun
// Scans docs/ADR/adr-*.md, parses frontmatter, and regenerates index.yaml.
// Usage: regenerate-adr-index.ts <adrDir> <indexPath>
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, relative } from 'node:path'

type Frontmatter = Record<string, string> & { _raw: string }

const extractNumber = (filename: string): number => {
  const match = filename.match(/adr-(\d+)/)
  return match ? Number.parseInt(match[1], 10) : 999999
}

const parseFrontmatter = (text: string): Frontmatter | null => {
  if (!text.startsWith('---\n')) return null
  const end = text.indexOf('---\n', 4)
  if (end === -1) return null
  const fmText = text.slice(4, end)
  const fm: Record<string, string> = {}
  for (const line of fmText.split('\n')) {
    if (line.startsWith(' ') || line.startsWith('\t')) continue
    if (line.endsWith(':') && !line.includes(': ')) {
      fm[line.slice(0, -1).trim()] = ''
    } else if (line.includes(': ')) {
      const idx = line.indexOf(': ')
      const key = line.slice(0, idx).trim()
      const value = line
        .slice(idx + 2)
        .trim()
        .replace(/^"|"$/g, '')
      fm[key] = value
    }
  }
  return { ...fm, _raw: fmText }
}

const extractContextPaths = (raw: string): string[] => {
  const ctxMatch = raw.match(/context:\n((?: {2}- .+\n?)+)/)
  if (!ctxMatch) return []
  return ctxMatch[1]
    .split('\n')
    .filter((line) => line.trim().startsWith('-') && line.includes('path:'))
    .map((line) => line.split('path:', 2)[1].trim().replace(/^"|"$/g, ''))
}

const main = (): void => {
  const [adrDir, indexPath] = process.argv.slice(2)
  if (!existsSync(adrDir)) {
    console.log('No docs/ADR directory found — nothing to index.')
    return
  }
  const glob = new Bun.Glob('adr-*.md')
  const files = [...glob.scanSync({ cwd: adrDir })].sort(
    (a, b) => extractNumber(a) - extractNumber(b),
  )

  const missing: string[] = []
  const entries: Array<Record<string, unknown>> = []

  for (const filename of files) {
    const fullPath = `${adrDir}/${filename}`
    const rel = relative(`${adrDir}/..`, fullPath)
    const content = readFileSync(fullPath, 'utf8')
    const fm = parseFrontmatter(content)
    if (fm === null) {
      missing.push(rel)
      continue
    }
    const required = ['title', 'status', 'date']
    const absent = required.filter((field) => !fm[field])
    if (absent.length > 0) {
      missing.push(`${rel} (missing: ${absent.join(', ')})`)
      continue
    }
    const num = extractNumber(basename(filename))
    const entry: Record<string, unknown> = {
      path: rel,
      adr: `ADR-${String(num).padStart(3, '0')}`,
      title: fm.title,
      status: fm.status,
      date: fm.date,
    }
    if (fm.superseded_by) entry.superseded_by = fm.superseded_by
    const contextPaths = extractContextPaths(fm._raw)
    if (contextPaths.length > 0) entry.context = contextPaths
    entries.push(entry)
  }

  if (missing.length > 0) {
    console.error(
      'WARNING: files with missing frontmatter (excluded from index):',
    )
    for (const f of missing) console.error(`  ${f}`)
  }

  const lines = [
    '# Auto-generated by adr-capture skill. Do not edit manually.',
    `# Last updated: ${new Date().toISOString().slice(0, 10)}`,
    'entries:',
  ]
  for (const e of entries) {
    lines.push(`  - path: "${e.path}"`)
    lines.push(`    adr: "${e.adr}"`)
    lines.push(`    title: "${e.title}"`)
    lines.push(`    status: ${e.status}`)
    lines.push(`    date: ${e.date}`)
    if (e.superseded_by) lines.push(`    superseded_by: "${e.superseded_by}"`)
    if (Array.isArray(e.context)) {
      lines.push('    context:')
      for (const c of e.context) lines.push(`      - path: "${c}"`)
    }
  }

  writeFileSync(indexPath, `${lines.join('\n')}\n`)
  console.log(`Generated ${entries.length} entries -> ${indexPath}`)
}

main()
