#!/usr/bin/env bash
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
ADR_DIR="$ROOT/docs/ADR"
INDEX="$ADR_DIR/index.yaml"

python3 - "$ADR_DIR" "$INDEX" <<'PYEOF'
import sys
import re
from pathlib import Path
from datetime import date

adr_dir = Path(sys.argv[1])
index_path = Path(sys.argv[2])


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return None
    try:
        end = text.index("---\n", 4)
    except ValueError:
        return None
    fm_text = text[4:end]
    fm = {}
    for line in fm_text.splitlines():
        if not line.startswith(" ") and not line.startswith("\t"):
            if line.endswith(":") and ": " not in line:
                k = line.rstrip(":").strip()
                fm[k] = ""
            elif ": " in line:
                k, _, v = line.partition(": ")
                fm[k.strip()] = v.strip().strip('"')
    fm["_raw"] = fm_text
    return fm


def extract_number(filename):
    m = re.search(r"adr-(\d+)", filename)
    return int(m.group(1)) if m else 999999


entries = []
missing = []

for md in sorted(adr_dir.glob("adr-*.md"), key=lambda p: extract_number(p.name)):
    rel = str(md.relative_to(adr_dir.parent))
    content = md.read_text()
    fm = parse_frontmatter(content)
    if fm is None:
        missing.append(rel)
        continue
    required = ["title", "status", "date"]
    absent = [f for f in required if not fm.get(f)]
    if absent:
        missing.append(f"{rel} (missing: {', '.join(absent)})")
        continue

    num = extract_number(md.name)
    entry = {
        "path": rel,
        "adr": f"ADR-{num:03d}",
        "title": fm["title"],
        "status": fm["status"],
        "date": fm["date"],
    }
    if "superseded_by" in fm and fm["superseded_by"]:
        entry["superseded_by"] = fm["superseded_by"]
    if "context" in fm:
        ctx_match = re.search(r"context:\n((?:  - .+\n?)+)", fm["_raw"])
        if ctx_match:
            items = [
                ln.split("path:", 1)[1].strip().strip('"')
                for ln in ctx_match.group(1).splitlines()
                if ln.strip().startswith("-") and "path:" in ln
            ]
            if items:
                entry["context"] = items
    entries.append(entry)

if missing:
    print("WARNING: files with missing frontmatter (excluded from index):", file=sys.stderr)
    for f in missing:
        print(f"  {f}", file=sys.stderr)

lines = [
    "# Auto-generated by adr-capture skill. Do not edit manually.",
    f"# Last updated: {date.today().isoformat()}",
    "entries:",
]
for e in entries:
    lines.append(f'  - path: "{e["path"]}"')
    lines.append(f'    adr: "{e["adr"]}"')
    lines.append(f'    title: "{e["title"]}"')
    lines.append(f"    status: {e['status']}")
    lines.append(f"    date: {e['date']}")
    if e.get("superseded_by"):
        lines.append(f'    superseded_by: "{e["superseded_by"]}"')
    if e.get("context"):
        lines.append("    context:")
        for c in e["context"]:
            lines.append(f'      - path: "{c}"')

index_path.write_text("\n".join(lines) + "\n")
print(f"Generated {len(entries)} entries -> {index_path}")
PYEOF
