import { describe, expect, it } from 'bun:test'
import {
  buildOutstandingMessage,
  parseContextIndex,
} from './surface-outstanding-work'

const SAMPLE = `# Auto-generated by context-index skill. Do not edit manually.

plans:
  - path: ".context/plans/one.md"
    title: "Ship hooks"
    status: "active"
  - path: ".context/plans/two.md"
    title: "Plan: ADR Generator"
    status: "done"
follow-ups:
  - path: ".context/follow-ups/review.md"
    title: "Review PR"
    status: "active"
`

describe('parseContextIndex', () => {
  it('parses plans and follow-ups with quoted values and statuses', () => {
    const index = parseContextIndex(SAMPLE)
    expect(index.plans).toHaveLength(2)
    expect(index.followUps).toHaveLength(1)
    expect(index.plans[0]).toEqual({
      path: '.context/plans/one.md',
      title: 'Ship hooks',
      status: 'active',
    })
    expect(index.followUps[0]?.title).toBe('Review PR')
    expect(index.unparseable).toBeUndefined()
  })

  it('flags lines that match no pattern', () => {
    const index = parseContextIndex(
      'plans:\n  - path: "x"\n    title: "t"\n    status: "active"\n??garbage??\n',
    )
    expect(index.unparseable).toBe('??garbage??')
  })

  it('tolerates missing status fields', () => {
    const index = parseContextIndex('follow-ups:\n  - title: Plain\n')
    expect(index.followUps[0]).toEqual({ title: 'Plain' })
  })
})

describe('buildOutstandingMessage', () => {
  it('lists active entries grouped by section, follow-ups first', () => {
    const message = buildOutstandingMessage(parseContextIndex(SAMPLE))
    expect(message).toContain('## Outstanding work (.context/index.yaml)')
    expect(message).toContain('### Active Follow-ups')
    expect(message).toContain('- Review PR (.context/follow-ups/review.md)')
    expect(message).toContain('### Active Plans')
    expect(message).toContain('- Ship hooks (.context/plans/one.md)')
    expect(message).not.toContain('ADR Generator')
  })

  it('returns undefined when nothing is active', () => {
    const index = parseContextIndex(
      'plans:\n  - path: "x"\n    status: "done"\n',
    )
    expect(buildOutstandingMessage(index)).toBeUndefined()
  })

  it('reports unparseable input loudly', () => {
    const index = parseContextIndex('??garbage??\n')
    expect(buildOutstandingMessage(index)).toContain(
      'Outstanding work: UNAVAILABLE',
    )
  })
})
